### ISSUE TITLE
Support for trees with missing tip labels?

### ISSUE THREAD

**Issue by nzmacalasdair** [thibautjombart/treespace#3]
Hello,

I am hoping to use treespace to compare bacterial gene trees to try and identify patterns of recombination in the genome. However, my dataset is large enough so that even using a fairly strict cutoff for the core genome results in some genes being absent in some strains, so each of the gene trees ends up having a different set of tip labels. As far as I understand (Coljin and Plazzotta, 2017) the metric doesn't require the trees to have the same tip labels, so is it at all possible for this package to allow for the comparison of trees with different tip labels?

Many thanks!

**Comment by MichelleKendall** [comment]
Hi,

Yes the metric as calculated by the `treeDist` and `treespace` functions requires the trees to have identical label sets. However, we've just released some new work which allows comparison of trees where the labels don't match (under certain conditions). See the [bioRxiv preprint](https://doi.org/10.1101/251710) for full details or the latest [vignette](https://cran.r-project.org/web/packages/treespace/vignettes/tipCategories.html) which talks you through how to use the new functions. 

Hope that helps - let me know if I can clarify anything.

Cheers,

Michelle

**Comment by nzmacalasdair** [comment]
This is fantastic! Exactly what I was looking for. Many thanks!

**Comment by MichelleKendall** [comment]
No problem, very happy to hear it!
