### ISSUE TITLE
Missing GitHub release of the version released on CRAN

### ISSUE THREAD

**Issue by maciejmotyka** [thibautjombart/treespace#6]
Hi,
was trying to decide whether to install `Treespace` from CRAN or the current dev version via `remotes::install_github("thibautjombart/treespace")`. Since the CRAN version is not tagged as a release on GitHub it's hard to quickly tell how many and what kind of changes were introduced.
In the end, I checked the `Treespace` CRAN release date to infer what was committed since then.

Also, people who watch `Releases only` will not be notified of new versions if these are not tagged at GitHub.

**Comment by MichelleKendall** [comment]
Thanks for bringing this to my attention. I'll be doing a new CRAN release soon so I'll tag it on GitHub and make a note to keep doing so. Thanks!
