### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Hongjinwu** [thibautjombart/treespace#9]
Hi, I am trying to install treespace by command: install.packages("treespace"). But the installation stopped at compiling dependency : sf, and seems related to "gdal" and gdal dependencies.  Which version of those dependencies are recommended and are there standard protocol for installing treespace? Thanks
My environment Centos7 and R 4.0.2.

**Comment by MichelleKendall** [comment]
Hi, thanks for getting in touch and I'm sorry to hear it's not been straightforward. They're not direct dependencies and I'm struggling to see how they are used by treespace https://cran.r-project.org/web/packages/sf/index.html. Please could you give a bit more detail on the error message? And what happens if you try to install "sf"? Thanks.

**Comment by Hongjinwu** [comment]
Thank you the help!
Here, is my command: install.packages("treespace",configure.args='--with-gdal-config=/home/wuhj/software/gdal-3.3.1/apps/gdal-config --with-proj-lib=/home/wuhj/software/proj-6.0.0/build/lib') 

The error message is :
.........
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/share/gdal/pcs.csv readable... yes
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... ./gdal_proj: error while loading shared libraries: libgdal.so.29: cannot open shared object file: No such file or directory
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?
ERROR: configuration failed for package ‘sf’
* removing ‘/home/wuhj/software/R-4.0.2/library/sf’
ERROR: dependency ‘sf’ is not available for package ‘spdep’
* removing ‘/home/wuhj/software/R-4.0.2/library/spdep’
ERROR: dependency ‘spdep’ is not available for package ‘adegenet’
* removing ‘/home/wuhj/software/R-4.0.2/library/adegenet’
ERROR: dependency ‘adegenet’ is not available for package ‘adephylo’
* removing ‘/home/wuhj/software/R-4.0.2/library/adephylo’
ERROR: dependencies ‘adegenet’, ‘adephylo’ are not available for package ‘treespace’
* removing ‘/home/wuhj/software/R-4.0.2/library/treespace’


But, I got PROJ6 installed.
Thanks

**Comment by MichelleKendall** [comment]
Ok thanks for the detail. I'm sorry it's not something I've seen before and I can't seem to replicate it. Perhaps you can see what happens if you try `install.packages("sf")` on its own, and maybe raise an issue with them? Their repo is [here](https://github.com/r-spatial/sf).

**Comment by Hongjinwu** [comment]
OK. Thanks
